import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import Sidebar from "./_components/sidebar";
import { Toaster } from "./_components/ui/toaster";

export const metadata: Metadata = {
  title: "Gerenciador de tarefas",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins", // Define uma variável CSS opcional.
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased flex `}>
        <Sidebar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
